### ISSUE TITLE
Huge Problem With Bios After Final Release

### ISSUE THREAD

**Issue by e-senturk** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#24]
Hi, I've been using your clover for a while, it was working so far so good until the final catalina release. It triggered some bug on bios nvram part. My bios become unaccessable even after booted from instaler usb. I could be able to boot on windows or mac but when I tried to access bios just got blackscreen, then I tried to reflash bios via asus winflash tool but I couldn't because bios updates are installing into bios on asus devices sadly I got black screen again. I find a tool for ami bioses like ours, so I ve managed to fix the access bios but when I login catalina same thing happen again. Do you have any problem like that.

**Comment by e-senturk** [comment]
Anyone having this issue with that laptop just install emu-variable64.efi driver and rc scripts for this volume on clover. It brokes auto select on clover but its better than bios error.

**Comment by MohammadtaghiFarkhondekar** [comment]
FIXED in V10

**Comment by shivaluma** [comment]
upgrade to v10 but still facing this issues\

**Comment by MohammadtaghiFarkhondekar** [comment]
open the laptop door and Remove the bios battery....

**Comment by e-senturk** [comment]
No need to open laptop just reflash your bios nvram with ami bios tool

**Comment by e-senturk** [comment]
Issue still happening because osxaptio fix v1 we need to use only v2

**Comment by MohammadtaghiFarkhondekar** [comment]
How did you flash your bios? please send your tools link

**Comment by e-senturk** [comment]
> How did you flash your bios? please send your tools link

https://www.bios-mods.com/tools/index.php?dir=AMI+Flash+Tools+%28Aptio+and+AMI%29%2F&download=amiflash.zip
download that zip and flash it with Aptio\afuwin\64\AfuWin64\AFUWINGUI.exe

**Comment by iSWORD** [comment]
Why is this closed? I got this after installing V10.

By the way, thank you so much @MohammadtaghiFarkhondekar for sharing your efforts with all of us.

**Comment by MohammadtaghiFarkhondekar** [comment]
I will work again ...

**Comment by e-senturk** [comment]
I switched to opencore succesfully any after its nvram reset option I ve get rid of that problem. Also it might related with vsmc boot arg.

**Comment by iSWORD** [comment]
@valinor61 thanks for the update. Is this something you could submit as a PR to this repo to help us all? How can I do this on my machine?

**Comment by MohammadtaghiFarkhondekar** [comment]
I fixed it . Yesterday I will update project to v11 .

**Comment by e-senturk** [comment]
Without opencore or the tool I ve send it cant be fixed this error needs a nvram reset if anyone interested in I shared my opencore build based on that clover please add your system serial mlb rom and uuid value with opencore configurator in to the generic section. And add boot/opencore.efi to as a new boot option in bios if you cant access to the bios first use the file I send earlier (its on few post before) reflash your bios with all section. Expecially nvram part.
[OpenCoreGL553VD.zip](https://github.com/MohammadtaghiFarkhondekar/macOS-Mojave-For-Asus-ROG-GL553VD/files/3991256/OpenCoreGL553VD.zip)

**Comment by MohammadtaghiFarkhondekar** [comment]
V11 now is ready !
